apiVersion: v1
kind: Service
metadata:
  name: bikemicroservices
  labels:
    app: bikemicroservices
spec:
  ports:
  - port: 3001
    targetPort: http-server
  selector:
    app: bikemicroservices
  type: LoadBalancer